// Nihilist Penguen - Soru destesi
// Her kart iki secenek sunar. Amac cogunlugun disinda kalmaktir.
const QUESTIONS = [
  { a: "Yüksek sesle video izleyen", b: "Telefonda hoparlörde konuşan", q: "Hangisini toplu taşımada görünce göz devirirsin?" },
  { a: "Uzaktan kumanda", b: "Çamaşır makinesi", q: "Hangisi evde daha sık kavga sebebidir?" },
  { a: "Sesli mesaj atan", b: "Habersiz arayan", q: "Hangisi daha çok sinir bozar?" },
  { a: "Geç kalan arkadaş", b: "Planı son anda iptal eden arkadaş", q: "Hangisini affetmek daha zor?" },
  { a: "Asansörde sessizlik", b: "Asansörde zorlama sohbet", q: "Hangisi daha dayanılmaz?" },
  { a: "Kışın soğuk ev", b: "Yazın sıcak ev", q: "Hangisine daha zor katlanırsın?" },
  { a: "Sabah insanı", b: "Gece kuşu", q: "Hangisi sensin?" },
  { a: "Ananaslı pizza", b: "Ketçaplı makarna", q: "Hangisi daha büyük suç?" },
  { a: "Grup sohbetinden sessizce çıkmak", b: "Bildirimleri kapatıp yok saymak", q: "Hangisini yaparsın?" },
  { a: "Sırasını bekleyemeyen", b: "Kasada bozuk para arayan", q: "Markette hangisi daha çok yorar?" },
  { a: "Spoiler veren", b: "Film boyunca soru soran", q: "Hangisiyle bir daha film izlemezsin?" },
  { a: "Okumadan onaylamak", b: "Kullanım koşullarını okumak", q: "Hangisi daha çok sana benziyor?" },
  { a: "Kamera açık toplantı", b: "İki saatlik e-posta trafiği", q: "Hangisini seçersin?" },
  { a: "Sabah alarmı ertelemek", b: "İlk alarmda kalkmak", q: "Hangisi senin gerçeğin?" },
  { a: "Yolda tanıdıkla karşılaşmak", b: "Boş bir otobüste yan koltuğa oturulması", q: "Hangisi daha rahatsız edici?" },
  { a: "Klimayı 18'e çeken", b: "Camı sonuna kadar açan", q: "Arabada hangisi daha çok tartışma çıkarır?" },
  { a: "Sürekli fotoğraf çeken", b: "Hiç fotoğraf çekmeyen", q: "Tatilde hangisiyle gitmek daha zor?" },
  { a: "Sesli yemek yiyen", b: "Tabakta yemek bırakan", q: "Hangisi daha çok gözüne batar?" },
  { a: "Borcunu unutan arkadaş", b: "Hesabı kuruşuna kadar bölen arkadaş", q: "Hangisi daha çok sinir bozar?" },
  { a: "Bir hafta internetsiz", b: "Bir hafta müziksiz", q: "Hangisine dayanabilirsin?" },
  { a: "Toplu taşımada ayakta", b: "Trafikte arabada oturarak", q: "Aynı sürede hangisi daha iyi?" },
  { a: "Söz verip gelmeyen", b: "Hiç söz vermeyen", q: "Hangisi daha dürüst?" },
  { a: "Yeni telefon", b: "Eski telefon, yeni şarj cihazı", q: "Hangisi hayatını daha çok değiştirir?" },
  { a: "Herkesin bildiği şarkı", b: "Kimsenin bilmediği şarkı", q: "Arabada hangisini açarsın?" },
  { a: "Sosyal medyayı bırakmak", b: "Tatlıyı bırakmak", q: "Hangisi daha kolay?" },
  { a: "Fazla konuşan", b: "Hiç konuşmayan", q: "Uzun yolda hangisi yanında olsun?" },
  { a: "Kirli bulaşık", b: "Katlanmamış çamaşır", q: "Hangisi seni daha çok geriyor?" },
  { a: "Gereksiz toplantı", b: "Gereksiz mesaj grubu", q: "Hangisi daha çok zaman çalıyor?" },
  { a: "Sesli okuyan", b: "Omzundan ekrana bakan", q: "Hangisi daha çok sınır ihlali?" },
  { a: "Erken gelip beklemek", b: "Son dakika yetişmek", q: "Hangisi senin tarzın?" },
  { a: "Kediler", b: "Köpekler", q: "Hangisi tartışmasız daha iyi?" },
  { a: "Sıcak çay", b: "Soğuk kahve", q: "Zor bir günde hangisi kurtarır?" },
  { a: "Şaka yollu eleştiri", b: "Yüzüne dürüst eleştiri", q: "Hangisi daha az can yakar?" },
  { a: "Sürpriz parti", b: "Sessiz doğum günü", q: "Hangisini istersin?" },
  { a: "Yanlış hatırlayan", b: "Hiç hatırlamayan", q: "Hangisi daha kötü?" },
  { a: "Tek başına tatil", b: "Kalabalık aile tatili", q: "Hangisi daha dinlendirici?" },
  { a: "Whatsapp'ta 'peki'", b: "Whatsapp'ta okundu bırakmak", q: "Hangisi daha soğuk?" },
  { a: "Kuyrukta öne geçen", b: "Kuyruğu sessizce kabullenen", q: "Hangisini daha çok görürsün?" },
  { a: "Aynı diziyi tekrar izlemek", b: "Yeni bir dizi başlamak", q: "Yorgun bir akşam hangisi?" },
  { a: "Uçakta pencere kenarı", b: "Uçakta koridor kenarı", q: "Hangisi doğru cevap?" },
  { a: "Bahane üreten", b: "Hiç açıklama yapmayan", q: "Hangisi daha çok bozar?" },
  { a: "Herkesin övdüğü film", b: "Kimsenin duymadığı film", q: "Bu akşam hangisi?" },
  { a: "Sabah duşu", b: "Akşam duşu", q: "Hangisi daha mantıklı?" },
  { a: "Emoji yağmuru", b: "Nokta ile biten mesaj", q: "Hangisi daha ürkütücü?" },
  { a: "Yeni şehirde kaybolmak", b: "Kendi şehrinde sıkılmak", q: "Hangisini seçersin?" },
  { a: "Sesli asistanla konuşmak", b: "Müşteri hizmetlerini beklemek", q: "Hangisi daha az acı verici?" },
  { a: "Gereksiz alışveriş", b: "Gereksiz abonelik", q: "Hangisi cüzdanı daha çok yakıyor?" },
  { a: "Yalan söyleyip kırmamak", b: "Doğruyu söyleyip kırmak", q: "Hangisi daha doğru?" },
  { a: "Kitabın filmi", b: "Filmin kitabı", q: "Hangisi genelde daha iyi?" },
  { a: "Sabahları koşmak", b: "Geceleri yürümek", q: "Hangisi daha iyi hissettirir?" },
  { a: "Kalabalıkta yalnızlık", b: "Yalnızken kalabalık düşünceler", q: "Hangisi daha ağır?" },
  { a: "Randevuya 10 dakika erken", b: "Randevuya 10 dakika geç", q: "Hangisi daha az sorun?" },
  { a: "Bardağı yarısı dolu görmek", b: "Bardağın kirli olduğunu fark etmek", q: "Hangisi daha gerçekçi?" },
  { a: "İş arkadaşıyla arkadaş olmak", b: "Arkadaşıyla iş yapmak", q: "Hangisi daha riskli?" },
  { a: "Herkesin haklı olduğu tartışma", b: "Kimsenin haklı olmadığı tartışma", q: "Hangisi daha yorucu?" },
  { a: "Telefonu şarjda unutmak", b: "Şarj aletini evde unutmak", q: "Hangisi daha büyük felaket?" },
  { a: "Plan yapmayı sevmek", b: "Plansız takılmayı sevmek", q: "Hangisi sensin?" },
  { a: "Övgüyü kabul edememek", b: "Eleştiriyi kabul edememek", q: "Hangisi daha yaygın?" },
  { a: "Sessiz sinema", b: "Karaoke", q: "Kalabalıkta hangisini oynarsın?" },
  { a: "Grup fotoğrafında en arkada", b: "Fotoğrafı çeken kişi olmak", q: "Hangisi senin yerin?" },
  { a: "Aynı yemeği her gün", b: "Her gün bilinmeyen bir yemek", q: "Bir ay boyunca hangisi?" },
  { a: "Sabah trafiği", b: "Akşam trafiği", q: "Hangisi ruhu daha çok yıpratır?" },
  { a: "Gizli hayran olmak", b: "Açıkça söyleyip reddedilmek", q: "Hangisi daha iyi?" },
  { a: "Kimsenin sormadığı fikri söylemek", b: "Sorulunca susmak", q: "Hangisi daha çok senlik?" },
  { a: "Herkesin gittiği yer", b: "Kimsenin bilmediği yer", q: "Tatilde hangisi?" },
  { a: "Bir saat geç uyumak", b: "Bir saat erken kalkmak", q: "Hangisi daha kolay?" },
  { a: "Yanlışı savunmak", b: "Haklıyken susmak", q: "Hangisini daha çok yaptın?" },
  { a: "Sonu belli film", b: "Sonu anlaşılmayan film", q: "Hangisi daha iyi?" },
  { a: "Mesajı yazıp silmek", b: "Yazmadan vazgeçmek", q: "Hangisi daha çok başına geldi?" },
  { a: "Kalabalık restoranda beklemek", b: "Boş restorana şüpheyle girmek", q: "Hangisini seçersin?" },
  { a: "Sürüye uymak", b: "Tek başına kalmak", q: "Hangisi daha güvenli?" }
];

if (typeof module !== "undefined") { module.exports = QUESTIONS; }
